### ISSUE TITLE
Why it is empty, waitting for the code, thank you!

### ISSUE THREAD

**Issue by colinchang2019** [wuchlei/AAAI20-Viewport-Prediction#1]

**Comment by wuchlei** [comment]
Sorry, no one has asked me for the code yet. So I got a little procrastination on the code refactoring. Will upload the code soon.

**Comment by colinchang2019** [comment]
> Sorry, no one has asked me for the code yet. So I got a little procrastination on the code refactoring. Will upload the code soon.

Thank you, waitting for u.

**Comment by wuchlei** [comment]
Code uploaded
